src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from lms import settings

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/', include('accounts.urls')),
    path('', index, name='index'),


    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    #
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/teachers/urls.py
from debug_toolbar import settings  # noqa

from django.urls import path

# from teachers.views import create_teachers, delete_teacher, get_teachers_with_filter, update_teacher
from teachers.views import TeacherCreateView, TeacherDeleteView, TeacherFilterView, TeacherUpdateView
from teachers.views import render_teachers_as_list, render_teachers_as_table

app_name = "teachers"

urlpatterns = [
    path('', render_teachers_as_table, name='table'),
    # path('filter', get_teachers_with_filter, name='filter'),
    path('list', render_teachers_as_list, name='list'),
    # path('create', create_teachers, name='new'),
    # path('update/<int:pk>', update_teacher, name='edit'),
    # path('delete/<int:pk>', delete_teacher, name='delete'),
    path('filter', TeacherFilterView.as_view(), name='filter'),
    path('create', TeacherCreateView.as_view(), name='new'),
    path('update/<int:pk>', TeacherUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', TeacherDeleteView.as_view(), name='delete'),

]

src/teachers/forms.py
"""
The module reciprocally processes HTML code and 'Python'-related one.
(App 'teachers')
"""
import datetime

import django_filters
from django.core.exceptions import ValidationError  # noqa
from django.forms import DateInput, ModelForm

from teachers.models import Teacher


class DateInputForm(DateInput):
    """
    This class is used to apply a custom HTML input model
    for attributes with type 'models.DateField'.
    """
    input_type = 'date'


class TeacherFilter(django_filters.FilterSet):

    class Meta:
        model = Teacher
        fields = {
            'first_name': ['exact', 'startswith', 'icontains'],
            'last_name': ['exact', 'startswith', 'icontains'],
            'age': ["exact", "gt", "gte", "lt", "lte"],
            'date_of_birth': ["exact"],
            'email': ["exact", "icontains"],
            'mobile_number': ["exact", "icontains"],
            'education': ["exact", "icontains"],
            'exp_years': ["exact", "gt", "gte", "lt", "lte"],
            'group': ["exact"]
        }
        widgets = {'date_of_birth': DateInputForm()}


class TeacherBaseForm(ModelForm):
    """
    A form that converts "python"-related data types of instance attributes
    into relevant HTML representation.
    """

    class Meta:
        model = Teacher
        # fields = ['first_name', "last_name", "age",
        #           "date_of_birth", "email", "mobile_number",
        #           "education", "exp_years"]
        fields = '__all__'
        widgets = {'date_of_birth': DateInputForm()}

    def as_p_br(self):
        """
        Returns the form rendered as HTML <p>s (with extra <break>'s).
        """
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(label)s <br/> %(field)s%(help_text)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    def clean_email(self):
        """
        Validates that the input email is unique.
        """
        email = self.cleaned_data['email']
        email_not_unique = Teacher.objects.filter(email=email).exclude(id=self.instance.id).exists()
        if email_not_unique:
            raise ValidationError("This email is not unique.")
        return email

    def clean(self):
        """
        Validates that the age and the date of birth of a teacher
        input through an HTML form mutually correspond.
        """
        age = self.cleaned_data['age']
        dob = self.cleaned_data['date_of_birth']
        validation = super().clean()
        if age and dob:
            today = datetime.date.today()
            verified_age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
            if age != verified_age:
                raise ValidationError('The input data in fields "Age" and "Date of Birth" do not match.')
        return validation


class TeacherCreateForm(TeacherBaseForm):
    model = Teacher
    pass


class TeacherUpdateForm(TeacherBaseForm):

    class Meta(TeacherBaseForm.Meta):
        model = Teacher

src/teachers/views.py
"""
Django module with view-functions (App 'teachers').
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect  # noqa
from django.shortcuts import render, get_object_or_404  # noqa
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from teachers.forms import TeacherCreateForm, TeacherFilter, TeacherUpdateForm
from teachers.models import Teacher
from teachers.tools import format_table, repack_query_set # noqa

# Create your views here.


def get_teachers(request):
    """
    This method outputs records from the DB table 'teachers_teacher'
    according to an SQL request depending on filter parameters.

    :param request: (str) a request received by the server from a client
    :return teachers: (QS) fetched from the table records on teachers

    Local variables:
    teachers: (QuerySet) records of the table 'teachers_teacher'
                         according to filter parameters
    params: (list) admissible SQL filtering parameters
    param_name: (str) one filtering parameter from the list
    param_value: (str) a value input as a certain parameter (param_name)
    param_merged: (str) one or several values of the parameter input by a client
    param_elems: (list) parameter values stripped of redundant space symbols
    param_elem: (str) one separate value from the list of parameter values
    or_filter: (Q) a filtering utility which
                   applies the logical operator "OR" to SQL requests
    """
    teachers = Teacher.objects.all()
    params = ['first_name',
              'first_name__startswith',
              'first_name__endswith',
              'last_name',
              'last_name__startswith',
              'last_name__endswith',
              'age',
              'age__gt',
              'age__gte',
              'age__lt',
              'age__lte',
              'date_of_birth',
              'date_of_birth__startswith',
              'date_of_birth__endswith',
              'e_mail',
              'e_mail__startswith',
              'e_mail__endswith',
              'education',
              'education__startswith',
              'education__endswith',
              'mobile_number',
              'exp_years',
              'exp_year__gt',
              'exp_years__gte',
              'exp_years__lt',
              'exp_years__lte',
              'groups',
              'groups__startswith',
              'groups__endswith'
              ]
    for param_name in params:
        param_value = request.GET.get(param_name)
        if param_value:
            param_merged = param_value.split(',')
            param_elems = list(map(lambda x: x.strip(), param_merged))
            if param_elems:
                or_filter = Q()
                for param_elem in param_elems:
                    if isinstance(request.GET.get('precise'), str) or \
                            (param_name == 'age' or param_name == 'exp_years'):
                        or_filter |= Q(**{param_name: param_elem})
                    else:
                        or_filter |= Q(**{f'{param_name}__contains': param_elem})
                teachers = teachers.filter(or_filter)
            else:
                teachers = teachers.filter(**{param_name: param_value})
    return teachers


def render_teachers_as_table(request):
    """
    This method renders data on teachers as an HTML table.

    :param request: (str) a request received by the server from a client
    :return: (str) formed response with rendered HTML code

    Local variables:
    teachers: (QS) records of the table 'teachers_teacher'
                   according to filter parameters
    data: (list) results of an SQL query repacked into a list
    headers: (list) a list of the names of the table columns
    """
    teachers = get_teachers(request)
    data = repack_query_set(teachers)
    # try:
    #     headers = [f.verbose_name for f in teachers[0]._meta.fields]
    # except IndexError:
    #     headers = []
    return render(request, "teachers/teachers_get.html",
                  {"data": data})
    # {"headers": headers, "data": data})


def render_teachers_as_list(request):
    """
    This method renders data on teachers as HTML paragraphs.

    :param request: (str) a request received by the server from a client
    :return: (str) formed response with rendered HTML code

    Local variables:
    teachers: (QS) records of the table 'teachers_teacher'
                   according to filter parameters
    """
    teachers = get_teachers(request)
    return render(request=request,
                  template_name='teachers/teachers_list.html',
                  context={'records': teachers})


def get_teachers_with_filter(request):
    """
    This method outputs records from the DB table 'teachers_teacher'
    according to an SQL request formed with a 'django_filters.FilterSet'.

    :param request: (str) a request received by the server from a client
    :return: (str) formed response with rendered HTML code

    Local variables:
    teachers: (QS) all the records from the table 'teachers_teacher' of the DB.
    filt: ('django_filters.FilterSet') a class that renders preferred attributes of
                                       instances of the model "Teacher" into HTML code
    """
    teachers = Teacher.objects.all().select_related("group")
    # teachers = Teacher.objects.all()
    # headers = []
    # if teachers:
    #     headers = [f.verbose_name for f in teachers[0]._meta.fields]
    #     headers.extend(["🖉", "🗑"])
    filt = TeacherFilter(
        data=request.GET,
        queryset=teachers)
    return render(request=request,
                  template_name='teachers_filter/teachers_get_filter.html',
                  context={'filter': filt})
    # context={'filter': filt, "headers": headers})


def create_teachers(request):
    """
    This method generates a new teacher
    and adds him/her into the 'teachers_teacher' table of the DB.

    :param request: (str) a request received by the server from a client
    :return: (str) formed response with rendered formatted HTML code

    Local variables:
    form: (user's Modelform) parameters to post and input into the DB
                             reciprocally rendered into HTML and 'Python' code
    html_template: (str) HTML code to be rendered into the web-page
    result: (str) formatted HTML code with the values of parameters
                  rendered as paragraphs/redirects to the table 'teachers_teacher'
    """
    if request.method == 'POST':
        form = TeacherCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:filter'))
    elif request.method == 'GET':
        form = TeacherCreateForm()
    else:
        raise NotImplementedError('Only "GET"/"POST" methods are supported recently.')
    # return render(request, 'teachers/teachers_create.html', {"fields": form.as_p_br()})  # without 'FilterSet'
    return render(request, 'teachers/teachers_create.html', {"form": form})


def update_teacher(request, pk):
    """
    This method updates information on a teacher
    whose the table id is indicated as a parameter

    :param request: (str) a request received by the server from a client
    :param pk: (int) an id of a teacher in the table 'teachers_teacher'
    :return: (str) formed response with rendered formatted HTML code

    Local variables:
    teacher: (Teacher) a lecturer in the table with the specified id
    form: (user's Modelform) parameters to post and input into the DB
                             reciprocally rendered into HTML and 'Python' code
    """
    teacher = get_object_or_404(Teacher, id=pk)
    if request.method == 'POST':
        form = TeacherUpdateForm(data=request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:filter'))
    elif request.method == 'GET':
        form = TeacherUpdateForm(instance=teacher)
    else:
        raise NotImplementedError('Only "GET"/"POST" methods are supported recently.')
    return render(request=request,
                  template_name='teachers/teachers_update.html',
                  # context={'fields': form.as_p_br(),  # without 'FilterSet'
                  context={'form': form,
                           'id': pk,
                           'teacher': teacher})


def delete_teacher(request, pk):
    """
    This method deletes a specified teacher
    from the relevant table of the DB.

    :param request: (str) a request received by the server from a client
    :param pk: (int) an id of a teacher in the table 'teachers_teacher'
    :return: (str) formed response with rendered formatted HTML code

    Local variables:
    teacher: (Teacher) a lecturer in the table with the specified id
    """
    teacher = get_object_or_404(Teacher, id=pk)
    if request.method == 'POST':
        teacher.delete()
        return HttpResponseRedirect(reverse('teachers:filter'))
    return render(request=request,
                  template_name='teachers/teachers_delete.html',
                  context={'teacher': teacher})


class TeacherFilterView(LoginRequiredMixin, ListView):
    """
    Searches and filters teachers.
    """
    model = Teacher
    template_name = 'teachers_filter/teachers_get_filter.html'
    login_url = reverse_lazy('accounts:login')
    paginate_by = 10
    context_object_name = 'teachers'

    def get_filter(self):
        return TeacherFilter(
               data=self.request.GET,
               queryset=self.model.objects.all()
               )

    def get_queryset(self):
        return self.get_filter().qs.select_related("group")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

src/teachers/templates/teachers/teachers_create.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}


    {% block main %}
       <form method='post' style='margin-left: 20pt'>
            {% csrf_token %}
            <h2>Create a new record in the table 'Teachers' of the DB.<br><br></h2>
            {{ form|crispy }}<br>
            <input type="submit" value="Create a teacher" class="btn btn-success">
            <button onclick="location.href='{% url 'teachers:filter' %}'" type="button" style="margin-left: 10pt;" class="btn btn-primary">
                Back to the table
            </button>
           <br><br>
        </form>
    {% endblock %}

src/teachers/templates/teachers/teachers_delete.html
{% extends 'base.html'%}

    {% block main %}
    <form method='post'>
    {% csrf_token %}
        <h2>Do You confirm the delete of {{teacher.first_name}} {{teacher.last_name}}, # ID {{teacher.id}}?<br><br></h2>
        <input type="submit" class="btn btn-danger" value="Delete this teacher">
         <button onclick="location.href='{% url 'teachers:filter' %}'" class="btn btn-info" type="button">
             Undo delete
         </button>
    </form>
    {% endblock %}

src/teachers/templates/teachers/teachers_get.html
{% extends 'table.html'%}


    {% block main %}
        <form>

            <h2>FILL IN THE NECESSARY DATA TO FETCH RECORDS FROM THE TABLE</h2>
            <br>
            <table style="text-align: center; margin-left: 50pt;">

                <tr>
                    <td><label>First name:</label><br></td>
                    <td><label>Last name:</label><br></td>
                    <td><label>Age (full years):</label><br></td>
                </tr>

                 <tr>
                    <td><input type="text" name="first_name" placeholder="Enter the first name"><br><br></td>
                    <td><input type="text" name="last_name" placeholder="Enter the last name"><br><br></td>
                    <td><input type="number" name="age" placeholder="Enter the age"><br><br></td>
                 </tr>

                <tr>
                    <td><label>Date of Birth:</label><br></td>
                    <td><label>E-mail:</label><br></td>
                    <td><label>Mobile number:</label><br></td>
                </tr>

                 <tr>
                    <td><input type="date" name="date_of_birth" placeholder="Enter the date of birth"><br><br></td>
                    <td><input type="text" name="email" placeholder="Enter the email"><br><br></td>
                    <td><input type="text" name="mobile_number" placeholder="Enter the phone number"><br><br></td>
                 </tr>

                <tr>
                    <td><label>Education:</label><br></td>
                    <td><label>Experience (years):</label><br></td>
                    <td><label>Groups:</label><br></td>
                </tr>

                 <tr>
                    <td><input type="text" name="education" placeholder="Enter the data"><br><br></td>
                    <td><input type="number" name="exp_years" placeholder="Enter the working experience"><br><br></td>
                    <td><input type="text" name="groups" placeholder="Enter current groups"><br><br></td>
                 </tr>

                 <tr>
                    <td>
                        <label>Precise search:</label>
                        <input type="checkbox" name="precise" placeholder="Precise search"><br><br>
                    </td>
                 </tr>

                 <tr>
                    <td><input type="submit" value="Search" class="btn btn-info"></td>
                    <td>
                         <button onclick="location.href='{% url 'teachers:new' %}'" type="button" class="btn btn-primary">
                             Create a new teacher
                        </button>
                    </td>
                     <td>
                         <button onclick="location.href='{% url 'teachers:list' %}'" type="button" class="btn btn-warning">
                             Edit teachers
                        </button>
                    </td>
                 </tr>

            </table>



            <br>
            <div>
                <br><b>HINT:</b> The search supports content filtration (except: 'age', 'date of birth', 'experience').
            </div>
            <div style="padding-left: 3em;">
                Apply several symbols that are contained in a field to get the relevant response.
            </div>

        </form>
    {% endblock %}

    {% block wide %}width: 125%{% endblock %}

src/teachers/templates/teachers/teachers_list.html
{% extends 'base.html'%}

    {% block main %}
        {%block action%}
            <h2 style="text-align: center;">Update or delete existing records in the table 'Teachers' of the DB.</h2>
        {% endblock %}
    <br>
    <table style="margin-left: auto; margin-right: auto; text-align: center;">
        <tr>
            <th>TEACHER<br><br></th>
        </tr>
        {% for record in records %}
            <tr>
                <td style="text-align: left;">
                    &nbsp;
                    <a href="{% url 'teachers:edit' record.id %}" class="btn btn-warning" >UPDATE</a>&nbsp;|&nbsp;
                    <a href="{% url 'teachers:delete' record.id %}" class="btn btn-danger">DELETE</a>&nbsp;|&nbsp;
                    # ID: {{ record.id }} || {{record.last_name}}, {{record.first_name}}
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td>
                <br>
                <button onclick="location.href='{% url 'teachers:table' %}'" type="button" class="btn btn-primary">
                    Back to the table
                </button>
            </td>
        </tr>
    </table>

    <br><br>
    {% endblock %}

src/teachers/templates/teachers/teachers_update.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

    {% block main %}
       <form method='post' style='margin-left: 20pt'>
            {% csrf_token %}
            <h2>Update an existing record on a teacher with id №{{ id }}<br> in the table 'Teachers' of the DB.<br><br></h2>
            {{ form|crispy }}
                <br>
            <input type="submit" value="Update the teacher" class="btn btn-warning">
            <button onclick="location.href='{% url 'teachers:filter' %}'" type="button" style="margin-left: 10pt;" class="btn btn-primary">
                Undo alterations
            </button>
           <br><br>
       </form>
    {% endblock %}