src/groups/urls.py
from debug_toolbar import settings  # noqa

from django.urls import path

# from groups.views import create_groups, delete_group, get_groups_with_filter, update_group
from groups.views import GroupCreateView, GroupDeleteView, GroupFilterView, GroupUpdateView  # noqa
from groups.views import render_groups_as_list, render_groups_as_table


app_name = "groups"

urlpatterns = [
    path('', render_groups_as_table, name='table'),
    # path('filter', get_groups_with_filter, name='filter'),
    # path('create', create_groups, name="new"),
    path('list', render_groups_as_list, name="list"),
    # path('update/<int:pk>', update_group, name='edit'),
    # path('delete/<int:pk>', delete_group, name='delete'),
    path('filter', GroupFilterView.as_view(), name='filter'),
    path('create', GroupCreateView.as_view(), name='new'),
    path('update/<int:pk>', GroupUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', GroupDeleteView.as_view(), name='delete')

]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from lms import settings

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/', include('accounts.urls')),
    path('', index, name='index'),


    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    #
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/forms.py
"""
The module reciprocally processes HTML code and 'Python'-related one.
(App 'groups')
"""
from django.core.exceptions import ValidationError
from django.db import IntegrityError  # noqa
from django.forms import ChoiceField, ModelForm

import django_filters

from groups.models import Group

from students.models import Student  # noqa


class GroupFilter(django_filters.FilterSet):

    class Meta:
        model = Group
        fields = {
            'group_name': ["exact", "icontains"],
            # 'subject_name': ["exact", "icontains"],
            # 'lecturer': ["exact"],
            'teachers': ["exact"],
            'mentor': ["exact", "icontains"],
            'students': ["exact"],
            'average_score': ["exact", "gt", "gte", "lt", "lte"],
            "headman": ["exact"]
        }


class GroupBaseForm(ModelForm):
    """
    A form that converts "python"-related data types of instance attributes
    into relevant HTML representation.
    """

    class Meta:
        model = Group
        fields = "__all__"

    def as_p_br(self):
        """
        Returns the form rendered as HTML <p>s (with extra <break>'s).
        """
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(label)s <br/> %(field)s%(help_text)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
            )

    def clean_number_of_students(self):
        """
        The method validates the applicability of values
        transferred as the parameter 'number_of_students'.
        """
        number = self.cleaned_data['number_of_students']
        if number and (number < 14 or number > 30):
            raise ValidationError('The group is supposed be '
                                  'of no less than 14 '
                                  'and no more than 30 students.')
        return number

    def clean_average_score(self):
        """
        The method validates the applicability of values
        transferred as the parameter 'average_score'.
        """
        score = self.cleaned_data['average_score']
        if score and (score < 50 or score > 100):
            raise ValidationError('Admissible diapason: from 50 to 100 points.')
        return score


class GroupCreateForm(GroupBaseForm):
    """
    Renders the code into HTML when a new group is created.
    """

    class Meta(GroupBaseForm.Meta):
        exclude = ['headman']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        group_students = [(st.id, st.get_full_name()) for st in self.instance.students.all()]
        self.fields['Headman'] = ChoiceField(choices=group_students, required=False)


#  -------------- COMPLICATED HEADMAN REALISATION --------------- #
# class GroupUpdateForm(GroupBaseForm):
#     """
#     Renders the code into HTML when a  group is updated.
#     """
#
#     class Meta(GroupBaseForm.Meta):
#         fields = ["group_name", "mentor",
#                   "average_score"]
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         group_students = [(st.id, st.get_full_name()) for st in self.instance.students.all()]
#         if group_students and self.instance.__dict__.get('headman'):
#             self.fields['Headman'] = ChoiceField(choices=group_students,
#                                                  initial=str(self.instance.headman.id),
#                                                  required=False
#                                                  )
#         else:
#             self.fields['Headman'] = ChoiceField(choices=group_students,
#                                                  required=False
#                                                  )
#
#     def save(self, commit=True):
#         pk = self.cleaned_data.get('Headman')
#         if pk:
#             headman = Student.objects.get(id=pk)
#             self.instance.headman = headman
#         return super().save(commit)


# ------------------ NOT FUNCTIONING PROPERLY ------------------------
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     students_qs = self.form_qs(Student)
    #     teachers_qs = self.form_qs(Teacher)
    #
    #     students = [(st.id, st.get_full_name()) for st in students_qs]
    #     teachers = [(teacher.id, teacher.get_full_name()) for teacher in teachers_qs]
    #     group_students = [(st.id, st.get_full_name()) for st in self.instance.students.all()]
    #     self.fields['Students'] = ChoiceField(choices=students, required=False)
    #     # (IF THERE IS NO HEADMAN IN THE GROUP,
    #     #  TRYING TO ACCESS THE 'id' field of a 'NoneType' instance raises an ATTRIBUTE.ERROR)
    #     try:
    #         self.fields['Headman'] = ChoiceField(choices=group_students,
    #                                              initial=str(self.instance.headman.id),
    #                                              required=False
    #                                              )
    #     except AttributeError:
    #         self.fields['Headman'] = ChoiceField(choices=group_students,
    #                                              required=False
    #                                              )
    #     self.fields['Lecturer'] = ChoiceField(choices=teachers, required=False)

    # def save(self, commit=True):
    #     # (IF NO HEADMAN IS SELECTED,
    #     #  THE CODE RAISES A VALUE.ERROR: wrong data type in the field 'id') [ --> line 122 of this module ]
    #     try:
    #         headman = Student.objects.get(id=self.cleaned_data['Headman'])
    #         self.instance.headman = headman
    #     except ValueError:
    #         pass
    #     return super().save(commit)

# ---------------------------
# Alternative working HEADMAN realisation


class GroupUpdateForm(GroupBaseForm):

    class Meta(GroupBaseForm.Meta):
        fields = ["group_name", "mentor",
                  "average_score", "headman"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['headman'].queryset = self.instance.students.all()
# ---------------------------

src/groups/views.py
"""
Django module with view-functions (App 'groups').
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404  # noqa
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from groups.forms import GroupCreateForm, GroupFilter, GroupUpdateForm
from groups.models import Group
from groups.tools import repack_query_set

# Create your views here.
from students.models import Student  # noqa


def get_groups(request):
    """
    This method outputs records from the DB table 'groups_group'
    according to an SQL request depending on filter parameters.

    :param request: (str) a request received by the server from a client
    :return groups: (QS) fetched from the table records on groups

    Local variables:
    groups: (QuerySet) records of the table 'groups_group'
                       according to filter parameters
    params: (list) admissible SQL filtering parameters
    param_name: (str) one filtering parameter from the list
    param_value: (str) a value input as a certain parameter (param_name)
    param_merged: (str) one or several values of the parameter input by a client
    param_elems: (list) parameter values stripped of redundant space symbols
    param_elem: (str) one separate value from the list of parameter values
    or_filter: (Q) a filtering utility which
                   applies the logical operator "OR" to SQL requests


    """
    groups = Group.objects.all()
    params = ['group_name',
              'group_name__startswith',
              'group_name__endswith',
              'subject_name',
              'subject_name__startswith',
              'subject_name__endswith',
              'lecturer',
              'lecturer__startswith',
              'lecturer__endswith',
              'mentor',
              'mentor__startswith',
              'mentor__endswith',
              'number_of_students',
              'number_of_students__gt',
              'number_of_students__gte',
              'number_of_students__lt',
              'number_of_students__lte',
              'average_score',
              'average_score__gt',
              'average_score__gte',
              'average_score__lt',
              'average_score__lte'
              ]
    for param_name in params:
        param_value = request.GET.get(param_name)
        if param_value:
            param_merged = param_value.split(',')
            param_elems = list(map(lambda x: x.strip(), param_merged))
            if param_elems:
                or_filter = Q()
                for param_elem in param_elems:
                    if param_name == 'number_of_students' or param_name == 'average_score':
                        or_filter |= Q(**{param_name: param_elem})
                    else:
                        or_filter |= Q(**{f'{param_name}__contains': param_elem})
                groups = groups.filter(or_filter)
            else:
                groups = groups.filter(**{param_name: param_value})
    return groups


def render_groups_as_table(request):
    """
    This method renders data on groups as an HTML table.

    :param request: (str) a request received by the server from a client
    :result: (str) formatted HTML code with the values of parameters

    Local variables:
    groups: (QS) records of the table 'groups_group'
                 according to filter parameters
    data: (list) results of an SQL query repacked into a list
    headers: (list) a list of the names of the table columns
    """
    groups = get_groups(request)
    data = repack_query_set(groups)
    try:
        headers = [f.verbose_name for f in groups[0]._meta.fields]
    except IndexError:
        headers = []
    return render(request, "groups/groups_get.html",
                  {"headers": headers, "data": data})


def render_groups_as_list(request):
    """
    This method renders data on groups as HTML paragraphs.

    :param request: (str) a request received by the server from a client
    :result: (str) formatted HTML code with the values of parameters

    Local variables:
    groups: (QS) records of the table 'groups_group'
                 according to filter parameters
    """
    groups = (get_groups(request))
    return render(request=request,
                  template_name='groups/groups_list.html',
                  context={'records': groups})


def get_groups_with_filter(request):
    """
    This method outputs records from the DB table 'groups_group'
    according to an SQL request formed with a 'django_filters.FilterSet'.

    :param request: (str) a request received by the server from a client
    :return: (str) formed response with rendered HTML code

    Local variables:
    groups: (QS) all the records from the table 'groups_group' of the DB.
    filt: ('django_filters.FilterSet') a class that renders preferred attributes of
                                       instances of the model "Group" into HTML code
    """
    groups = Group.objects.all().select_related("headman", "subject").prefetch_related('students', 'teachers')
    # headers = []
    # if groups:
    #     headers = [f.verbose_name for f in Group.objects.last()._meta.fields]
    #     headers.extend(["🖉", "🗑"])
    filt = GroupFilter(
        data=request.GET,
        queryset=groups)
    return render(request=request,
                  template_name='groups_filter/groups_get_filter.html',
                  context={'filter': filt})
    # context={'filter': filt,'headers': headers})


def create_groups(request):
    """
    This method generates a new group
    and adds it into the 'groups_group' table of the DB.

    :param request: (str) a request received by the server from a client
    :return: (str) formed response with rendered formatted HTML code

    Local variables:
    form: (user's Modelform) parameters to post and input into the DB
                             reciprocally rendered into HTML and 'Python' code
    html_template: (str) HTML code to be rendered into the web-page
    result: (str) formatted HTML code with the values of parameters
                  rendered as paragraphs/redirects to the table 'groups_group'
    """
    if request.method == 'POST':
        form = GroupCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:filter'))
    elif request.method == 'GET':
        form = GroupCreateForm()
    else:
        raise NotImplementedError('Only "GET"/"POST" methods are supported recently.')
    # return render(request, 'groups/groups_create.html', {"fields": form.as_p_br()})  # without 'FilterSet'
    return render(request, 'groups/groups_create.html', {"form": form})


def update_group(request, pk):
    """
    This method updates information on a group
    the table id of which is indicated as a parameter

    :param request: (str) a request received by the server from a client
    :param pk: (int) an id of a group in the table 'groups_group'
    :return: (str) formed response with rendered formatted HTML code

    Local variables:
    group: (Group) a group in the table with the specified id
    form: (user's Modelform) parameters to post and input into the DB
                             reciprocally rendered into HTML and 'Python' code
    """
    group = get_object_or_404(Group, id=pk)
    if request.method == 'POST':
        form = GroupUpdateForm(data=request.POST, instance=group)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:filter'))
    elif request.method == 'GET':
        form = GroupUpdateForm(instance=group)
    else:
        raise NotImplementedError('Only "GET"/"POST" methods are supported recently.')
    return render(request=request,
                  template_name='groups/groups_update.html',
                  # context={'fields': form.as_p_br(),  # without 'FilterSet'
                  context={'form': form,
                           'id': pk,
                           # 'group': group})
                           'group': group,
                           'students': group.students.select_related('group', 'led_group').all(),
                           'teachers': group.teachers.select_related('group').all()})


def delete_group(request, pk):
    """
    This method deletes a specified group
    from the relevant table in the DB.

    :param request: (str) a request received by the server from a client
    :param pk: (int) an id of a group in the table 'groups_group'
    :return: (str) formed response with rendered formatted HTML code

    Local variables:
    group: (Group) a group in the table with the specified id

    """
    group = get_object_or_404(Group, id=pk)
    if request.method == 'POST':
        group.delete()
        return HttpResponseRedirect(reverse('groups:filter'))
    return render(request=request,
                  template_name='groups/groups_delete.html',
                  context={'group': group})


class GroupFilterView(LoginRequiredMixin, ListView):
    """
    Searches and filters groups.
    """
    model = Group
    template_name = 'groups_filter/groups_get_filter.html'
    login_url = reverse_lazy('accounts:login')
    paginate_by = 5
    context_object_name = 'groups'

    def get_filter(self):
        return GroupFilter(
               data=self.request.GET,
               queryset=self.model.objects.all()
               )

    def get_queryset(self):
        return self.get_filter().qs.select_related("headman", "subject").prefetch_related("students", "teachers")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        # context['groups'] = self.get_filter().qs.\

src/groups/templates/groups/groups_create.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}


    {% block main %}
       <form method='post' style='margin-left: 20pt'>
            {% csrf_token %}
            <h2>Create a new record in the table 'Groups' of the DB.<br><br></h2>
            {{ form|crispy }}<br>
            <input type="submit" value="Create a group" class="btn btn-success">
            <button onclick="location.href='{% url 'groups:filter' %}'" type="button" style="margin-left: 10pt;" class="btn btn-primary">
                Back to the table
            </button>
            <br><br>
        </form>
    {% endblock %}

src/groups/templates/groups/groups_delete.html
{% extends 'base.html'%}

    {% block main %}
    <form method='post'>
        {% csrf_token %}
        <h2>Do You confirm the delete of the group "{{group.group_name}}, # ID {{group.id}}?"<br><br></h2>
        <input type="submit" class="btn btn-danger" value="Delete this group">
         <button onclick="location.href='{% url 'groups:filter' %}'" class="btn btn-info" type="button">
             Undo delete
         </button>
    </form>
    {% endblock %}

src/groups/templates/groups/groups_get.html
{% extends 'table.html'%}

    {% block main %}
        <form>

            <h2>FILL IN THE NECESSARY DATA TO FETCH RECORDS FROM THE TABLE</h2>
            <br>

            <table style="text-align: center; margin-left: 50pt;">

                <tr>
                    <td><label>Group name:</label><br></td>
                    <td><label>Subject name:</label><br></td>
                </tr>

                 <tr>
                    <td><input type="text" name="group_name" placeholder="Enter the name of the group"><br><br></td>
                    <td><input type="text" name="subject_name" placeholder="Enter the name of the subject"><br><br></td>
                 </tr>

                <tr>
                    <td><label>Lecturer:</label><br></td>
                    <td><label>Mentor:</label><br></td>
                </tr>

                 <tr>
                    <td><input type="text" name="lecturer" placeholder="Enter the name of the lecturer"><br><br></td>
                    <td><input type="text" name="mentor" placeholder="Enter the name of the mentor"><br><br></td>
                 </tr>

                <tr>
                    <td><label>Number of students:</label><br></td>
                    <td><label>Average score (points):</label><br></td>
                </tr>

                 <tr>
                    <td><input type="number" name="number_of_students" placeholder="Enter the number of students"><br><br></td>
                    <td><input type="number" name="average_score"
                               placeholder="Enter the average score of the group"><br><br></td>
                 </tr>

                 <tr>
                    <td><input type="submit" value="Search" class="btn btn-info"></td>
                    <td>
                         <button onclick="location.href='{% url 'groups:new' %}'" type="button" class="btn btn-primary">
                             Create a new group
                        </button>
                    </td>
                     <td>
                         <button onclick="location.href='{% url 'groups:list' %}'" type="button" class="btn btn-warning">
                             Edit groups
                        </button>
                    </td>
                 </tr>

            </table>

            <br>
            <div style="margin-left: 50pt;">
                <div>
                    <b>HINT:</b> the search supports content filtration (except: 'average score', 'number of students').
                </div>
                <div style="padding-left: 3em;">
                    Apply several symbols that are contained in a field to get the relevant response.
                </div>
            </div>

        </form>
    {% endblock %}

    {% block wide %}width: 70%{% endblock %}

src/groups/templates/groups/groups_list.html
{% extends 'base.html'%}

    {% block main %}
        {%block action%}
            <h2 style="text-align: center;">Update or delete existing records in the table 'Groups' of the DB.</h2>
        {% endblock %}
    <br>
    <table style="margin-left: auto; margin-right: auto; text-align: center;">
        <tr>
            <th>GROUP<br><br></th>
        </tr>
        {% for record in records %}
            <tr>
                <td style="text-align: left;">
                    &nbsp;
                    <a href="{% url 'groups:edit' record.id %}" class="btn btn-warning">UPDATE</a>&nbsp;|&nbsp;
                    <a href="{% url 'groups:delete' record.id %}" class="btn btn-danger">DELETE</a>&nbsp;|&nbsp;
                    # ID: {{ record.id }} || {{record.group_name}}
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td>
                <br>
                    <button onclick="location.href='{% url 'groups:table' %}'" type="button" class="btn btn-primary">
                    Back to the table
                </button>
            </td>
        </tr>
    </table>

    <br><br>
    {% endblock %}

src/groups/templates/groups/groups_update.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}


    {% block main %}
       <form method='post' style='margin-left: 20pt'>
            {% csrf_token %}
            <h2>Update an existing record on a group with id №{{ id }} in the table 'Groups' of the DB.<br><br></h2>
            {{ form|crispy }}<br>
            <input type="submit" value="Update a group" class="btn btn-warning">
            <button onclick="location.href='{% url 'groups:filter' %}'" type="button" style="margin-left: 10pt;" class="btn btn-primary">
                Undo alterations
            </button>
           <br><br>
        </form>
   {% endblock %}

    {% block tabula %}
        {% if group.students.count %}
            <p>STUDENTS: </p>
<!--                % w students=group.students.all %-->
                    {% include 'students/inclusive/students_tabula.html' %}
<!--                % w %-->
                <br><br>
        {% endif %}

        {% if group.teachers.count %}
            <p>TEACHERS: </p>
            {% include 'teachers/inclusive/teachers_tabula.html' %}
            <br><br>
        {% endif %}
    {% endblock %}