src/accounts/urls.py
from accounts.views import AccountAndProfileUpdateView, AccountDeleteView, AccountLoginView, AccountLogoutView, \
    AccountPasswordChangeView, AccountRegistrationView
#   AccountRegistrationView, AccountUpdateView, AccountAndProfileUpdateView

from debug_toolbar import settings  # noqa

from django.urls import path

app_name = "accounts"

urlpatterns = [
    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    # path('profile', AccountUpdateView.as_view(), name='profile'),
    path('profile', AccountAndProfileUpdateView.as_view(), name='profile'),
    path('profile/password', AccountPasswordChangeView.as_view(), name='password'),
    path('profile/delete/<int:pk>', AccountDeleteView.as_view(), name='delete')

]

src/courses/urls.py
# from courses.views import create_course, delete_course, get_courses_with_filter, update_course
from courses.views import CourseCreateView, CourseDeleteView, CourseFilterView, CourseUpdateView

from debug_toolbar import settings  # noqa

from django.urls import path

app_name = "courses"


urlpatterns = [
    # path('filter', get_courses_with_filter, name='filter'),
    # path('create', create_course, name='new'),
    # path('update/<int:pk>', update_course, name='edit'),
    # path('delete/<int:pk>', delete_course, name='delete'),
    path('filter', CourseFilterView.as_view(), name='filter'),
    path('create', CourseCreateView.as_view(), name='new'),
    path('update/<int:pk>', CourseUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', CourseDeleteView.as_view(), name='delete')
]

src/groups/urls.py
from debug_toolbar import settings  # noqa

from django.urls import path

# from groups.views import create_groups, delete_group, get_groups_with_filter, update_group
from groups.views import GroupCreateView, GroupDeleteView, GroupFilterView, GroupUpdateView  # noqa
from groups.views import render_groups_as_list, render_groups_as_table


app_name = "groups"

urlpatterns = [
    path('', render_groups_as_table, name='table'),
    # path('filter', get_groups_with_filter, name='filter'),
    # path('create', create_groups, name="new"),
    path('list', render_groups_as_list, name="list"),
    # path('update/<int:pk>', update_group, name='edit'),
    # path('delete/<int:pk>', delete_group, name='delete'),
    path('filter', GroupFilterView.as_view(), name='filter'),
    path('create', GroupCreateView.as_view(), name='new'),
    path('update/<int:pk>', GroupUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', GroupDeleteView.as_view(), name='delete')

]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from lms import settings

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/', include('accounts.urls')),
    path('', index, name='index'),


    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    #
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from debug_toolbar import settings  # noqa

from django.urls import path

# from students.views import create_students, delete_student, get_students, update_students
from students.views import StudentCreateView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = "students"

urlpatterns = [
    # path('', get_students, name='list'),
    # path('create', create_students, name='create'),
    # path('update/<int:pk>', update_students, name='update'),
    # path('delete/<int:pk>', delete_student, name='delete'),
    path('', StudentListView.as_view(), name='list'),
    path('create', StudentCreateView.as_view(), name='create'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='delete')

]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
              integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
              crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

        <title>LMS</title>

        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <div class="container" style="text-align: center;">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <img src="{% static 'images/dt_logo.png' %}" alt="icon" style="width: 100px; height: 100px;">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">🏠</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'students:list' %}">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'teachers:filter' %}">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'groups:filter' %}">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'courses:filter' %}">Courses</a>
                        </li>
                    </ul>

<!--                    <form class="d-flex">-->
<!--                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--                        <button class="btn btn-primary" type="submit" style="margin-left: 10pt; color: white;">Search</button>-->
<!--                    </form>-->
                </div>

                {% if user.is_authenticated %}

                    <div class="navbar-nav">
                        <div class="nav-item" style="padding-right: 25pt;">
                            <img class="rounded-circle img-thumbnail" alt="avatar" style="width: 100px; height: 100px;" src="{{ user.profile.image.url }}">
                        </div>
                        <div class="nav-item" style="padding-right: 15pt;">
                            <a class="btn btn-success btn-outline-primary" style="color: black; margin-top: 20px;" aria-current="page" href="{% url 'accounts:profile' %}">PROFILE<br>&lt;&lt;{{user}}&gt;&gt;</a>
                        </div>
                        <div class="nav-item">
                            <a class="btn btn-primary btn-outline-warning" style="color: black; margin-top: 30px;" aria-current="page" href="{% url 'accounts:logout' %}">LOG OUT</a>
                        </div>
                    {% if user.is_superuser %}
                        <dir>
                            <a class="btn btn-info btn-outline-danger" style="color: black; margin-top: 8px;" aria-current="page" href="admin/">ADMIN</a>
                        </dir>
                    {% endif %}
                    </div>

                {% else %}

                    <div class="navbar-nav">
                        <div class="nav-item" style="padding-right: 15pt;">
                            <a class="btn btn-primary btn-outline-warning" style="color: black;" aria-current="page" href="{% url 'accounts:login' %}">LOG IN</a>
                        </div>
                        <div>
                            <a class="btn btn-success btn-outline-primary" style="color: black;" aria-current="page" href="{% url 'accounts:registration' %}">SIGN UP</a>
                        </div>
                    </div>
                {% endif %}

            </div>
        </nav>

        <style>
            {% block cascade %}
                head{
                    font-size: 22px;
                    font-family: Serif;
                }

                body{
                    font-size: 22px;
                    font-family: Serif;
                    }

                #tab{
                    {% block wide %}{% endblock %};
                        margin-left: auto;
                        margin-right: auto;
                        text-align: center;
                    }
            {% endblock %}
        </style>
        <br>
    </head>

    <body>

        <div class="container">

            {% include 'includes/messages.html' %}

            {% block main %}
                {% block action %}
                {% endblock %}
            {% endblock %}
        </div>

        <div id="tab">
            {% block tabula %}
            {% endblock %}
        </div>

        <div id="list">
            {% block list %}
            {% endblock %}
        </div>
    </body>

</html>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}

    {% block main %}
        <div class="card bg-dark text-black">
            <img src="{% static 'images/bg.png' %}" class="card-img" alt="background">
            <div class="card-img-overlay">
                <h3 style="text-align:center;">Tables</h3>
                <p>A table is an arrangement of data in rows and columns, or possibly in a more complex structure.</p>
                <p>Tables are widely used in communication, research, and data analysis.
                    Tables appear in print media, handwritten notes, computer software, architectural ornamentation, traffic signs, and many other places.
                    The precise conventions and terminology for describing tables vary depending on the context.
                </p>
                <p>Tables differ significantly in variety, structure, flexibility, notation, representation and use.
                    In books and technical articles, tables are typically presented apart from the main text in numbered and captioned floating blocks.
                </p>
            </div>
        </div>
    {% endblock %}

src/templates/table.html
{% extends 'base.html' %}

    {% block cascade %}
        body{
            font-size: 22px;
            font-family: Serif;
            }

        #data{
             border: 1px solid black; border-collapse: collapse; {% block wide %}{% endblock %};
             background-color: rgba(100, 100, 200, 0.2); text-align: center;
             letter-spacing: 1px; line-height: 1.5; margin-left: auto; margin-right: auto;
             }
    {% endblock %}

    {% block tabula %}
        {% if data %}
            <br>
            <table id="data">
                <tr style="border: 1px solid black; font-variant: small-caps;">
                    {% for header in headers %}
                        <th style="border: 1px solid black;">{{ header }}</th>
                    {% endfor %}
                </tr>

                {% for row in data %}
                    <tr style="border: 1px solid black;">
                        {% for cell in row %}
                            <td style="border: 1px solid black;">{{ cell }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <br><br>
        {% else %}
            <h1 style='margin-left: 750px;'><br>No records found on your query<br><br></h1>
        {% endif %}
    {% endblock %}