src/courses/urls.py
# from courses.views import create_course, delete_course, get_courses_with_filter, update_course
from courses.views import CourseCreateView, CourseDeleteView, CourseFilterView, CourseUpdateView

from debug_toolbar import settings  # noqa

from django.urls import path

app_name = "courses"


urlpatterns = [
    # path('filter', get_courses_with_filter, name='filter'),
    # path('create', create_course, name='new'),
    # path('update/<int:pk>', update_course, name='edit'),
    # path('delete/<int:pk>', delete_course, name='delete'),
    path('filter', CourseFilterView.as_view(), name='filter'),
    path('create', CourseCreateView.as_view(), name='new'),
    path('update/<int:pk>', CourseUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', CourseDeleteView.as_view(), name='delete')
]

src/lms/urls.py
from core.views import index

import debug_toolbar

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from lms import settings

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('accounts/', include('accounts.urls')),
    path('', index, name='index'),


    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('courses/', include('courses.urls')),
    #
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/courses/models.py
"""
Models of the app 'courses'.
"""
import random

from courses.model_tools import make_course

from django.db import models

# Create your models here.


class Course(models.Model):
    """
    The class represents a subject studied
    during the educational process.

    Group fields:
    course_name: (charfield) the name of the studied subject
    group: (foreignkey: 1to1) the group which studies the course
    teachers: (foreignkey: M2M) the lecturers who teach that subjects
    """

    class Difficulty(models.IntegerChoices):
        TRIVIAL = 0, 'Trivial'
        EASY = 1, 'Easy'
        MEDIUM = 2, 'Medium'
        EXPERT = 3, 'Expert'
        HARDCORE = 4, 'Hardcore'

    course_name = models.CharField(max_length=64, null=False, blank=False)
    group = models.OneToOneField(
        to='groups.Group',
        on_delete=models.SET_NULL,
        null=True,
        related_name='subject'
        )
    teachers = models.ManyToManyField(
        to='teachers.Teacher',
        null=True,
        related_name='courses'
        )
    difficulty = models.PositiveSmallIntegerField(
        choices=Difficulty.choices,
        default=Difficulty.EASY
    )

    def __str__(self):
        return f'#ID {self.id}: {self.course_name}'

    def get_info(self):
        output = f'Course: {self.course_name}'
        try:
            if self.group is not None:
                output += f' = Group: {self.group.group_name}'
        except AttributeError:
            pass

        try:
            output += f' = Teachers: {self.teachers}'
        except AttributeError:
            pass
        return output

    @classmethod
    def generate_courses(cls, count: int):
        if count <= 0:
            raise ValueError("Cannot add a negative or zero number of records into the DB.")
        for _ in range(count):
            obj = cls(
                      course_name=make_course(),
                      group=None,
                      difficulty=random.choice(cls.Difficulty.values)
                      )
            obj.save()

src/courses/forms.py
"""
THe module contains code that renders data
into HTML code for the app. 'courses'.
"""

from courses.models import Course

from django.forms import ModelForm

import django_filters


class CourseFilter(django_filters.FilterSet):
    """
    The class processes search and filtering operations.
    """

    class Meta:
        model = Course
        fields = {
            'course_name': ["exact", "icontains"],
            'group': ["exact"],
            "teachers": ["exact"]
        }


class CourseBaseForm(ModelForm):
    """
    A form that converts "python"-related data types of instance attributes
    into relevant HTML representation.
    """

    class Meta:
        model = Course
        fields = "__all__"
        # fields = ["group_name", "subject_name", "lecturer", "mentor",
        #           "number_of_students", "average_score"]


class CourseCreateForm(CourseBaseForm):
    pass


class CourseUpdateForm(CourseBaseForm):
    """
    The class operates the edit of the data about a course.
    """

    class Meta(CourseBaseForm.Meta):
        model = Course
        fields = '__all__'

src/courses/views.py
"""
The module contains view-functions for the app. 'courses'.
"""

from courses.forms import CourseCreateForm, CourseFilter, CourseUpdateForm
from courses.models import Course

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView


# Create your views here.


def get_courses_with_filter(request):
    """
    ...
    """
    courses = Course.objects.all().select_related("group").prefetch_related("teachers")
    filt = CourseFilter(
        data=request.GET,
        queryset=courses)
    return render(request=request,
                  template_name='courses/courses_get_filter.html',
                  context={'filter': filt,
                           'courses': filt.qs})


def create_course(request):
    """
    ...
    """
    if request.method == 'POST':
        form = CourseCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('courses:filter'))
    elif request.method == 'GET':
        form = CourseCreateForm()
    else:
        raise NotImplementedError('Only "GET"/"POST" methods are supported recently.')
    return render(request, 'courses/courses_create.html', {"fields": form})


def update_course(request, pk):
    """
    ...
    """
    course = get_object_or_404(Course, id=pk)
    if request.method == 'POST':
        form = CourseUpdateForm(data=request.POST, instance=course)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('courses:filter'))
    elif request.method == 'GET':
        form = CourseUpdateForm(instance=course)
    else:
        raise NotImplementedError('Only "GET"/"POST" methods are supported recently.')
    return render(request=request,
                  template_name='courses/courses_update.html',
                  context={'form': form,
                           'id': pk,
                           'course': course})


def delete_course(request, pk):
    """
    ...
    """
    course = get_object_or_404(Course, id=pk)
    if request.method == 'POST':
        course.delete()
        return HttpResponseRedirect(reverse('courses:filter'))
    return render(request=request,
                  template_name='courses/courses_delete.html',
                  context={'course': course})


class CourseFilterView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'courses/courses_get_filter.html'
    login_url = reverse_lazy('accounts:login')

    def get_filter(self):
        return CourseFilter(
               data=self.request.GET,
               queryset=self.model.objects.all()
               )

    # def get_queryset(self):
    #     return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        context['courses'] = self.get_filter().qs.select_related("group").prefetch_related("teachers")
        return context


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    form_class = CourseCreateForm
    success_url = reverse_lazy('courses:filter')
    template_name = 'courses/courses_create.html'
    login_url = reverse_lazy('accounts:login')


class CourseUpdateView(LoginRequiredMixin, UpdateView):

    model = Course
    form_class = CourseUpdateForm
    success_url = reverse_lazy('courses:filter')
    template_name = 'courses/courses_update.html'
    login_url = reverse_lazy('accounts:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['id'] = self.get_object().id
        return context


class CourseDeleteView(LoginRequiredMixin, DeleteView):

    model = Course
    success_url = reverse_lazy('courses:filter')
    template_name = 'courses/courses_delete.html'
    login_url = reverse_lazy('accounts:login')

src/courses/templates/courses/courses_create.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}


    {% block main %}
       <form method='post' style='margin-left: 20pt'>
            {% csrf_token %}
            <h2>Create a new record in the table 'Courses' of the DB.<br><br></h2>
            {{ form|crispy }}<br>
            <input type="submit" value="Create a course" class="btn btn-success">
            <button onclick="location.href='{% url 'courses:filter' %}'" type="button" style="margin-left: 10pt;" class="btn btn-primary">
                Back to the table
            </button>
           <br><br>
        </form>
    {% endblock %}

src/courses/templates/courses/courses_delete.html
{% extends 'base.html'%}

    {% block main %}
    <form method='post'>
    {% csrf_token %}
        <h2>Do You confirm the delete of the course {{course.course_name}}, # ID {{course.id}}?<br><br></h2>
        <input type="submit" class="btn btn-danger" value="Delete this course">
         <button onclick="location.href='{% url 'courses:filter' %}'" class="btn btn-info" type="button">
             Undo delete
         </button>
    </form>
    {% endblock %}

src/courses/templates/courses/courses_get_filter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

    {% block main %}

        {% block action %}
            <h2 style="text-align: center;"><br>THE LIST OF COURSES<br><br></h2>
        {% endblock %}

        <form method='get' style="padding-left: 50pt;">

            {{ filter.form|crispy }}

            <br><br>

            <input type="submit" class="btn btn-info" value="Submit">
            &nbsp;&nbsp;&nbsp;
            <a href="{% url 'courses:filter' %}" class="btn btn-primary">Reset filters</a>
            &nbsp;&nbsp;&nbsp;
            <a href="{% url 'courses:new' %}" class="btn btn-primary">Create a new course</a>

        </form>

        <br><br><br>

    {% endblock %}

    {% block tabula %}
        {% if filter.qs %}
            <table class="table table-bordered border-primary">
                <tr>
                    {% with headers='ID Course Group Teachers 🖉 🗑' %}
                        {% for header in headers.split %}
                            <th>{{ header }}</th>
                       {% endfor %}
                   {% endwith %}
                </tr>

                {% for course in courses %}
                    <tr>
                        <td>{{ course.id }}</td>
                        <td>{{ course.course_name }}</td>
                        <td>{{ course.group.group_name }}</td>
                        <td>
                            {% for teacher in course.teachers.all %}
                            <div>#ID{{ teacher.id }} {{ teacher.first_name }} {{ teacher.last_name }}</div>
                            {% endfor %}
                        </td>
                        <td><a href="{% url 'courses:edit' course.id %}" class="btn btn-warning">UPDATE</a></td>
                        <td><a href="{% url 'courses:delete' course.id %}" class="btn btn-danger">DELETE</a></td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <h1 style="margin-right: 350pt;">No records found on your query<br><br></h1>
        {% endif %}
    {% endblock %}

{% block wide %}width: 70%{% endblock %}

src/courses/templates/courses/courses_update.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

    {% block main %}
       <form method='post' style='margin-left: 20pt'>
            {% csrf_token %}
            <h2>Update an existing record on a teacher with id №{{ id }}<br> in the table 'Courses' of the DB.<br><br></h2>
            {{ form|crispy }}
            <input type="submit" value="Update the course" class="btn btn-warning">
            <button onclick="location.href='{% url 'courses:filter' %}'" type="button" style="margin-left: 10pt;" class="btn btn-primary">
                Undo alterations
            </button>
           <br><br>
       </form>
    {% endblock %}